### ISSUE TITLE
Limit discovery to only one network interface

### ISSUE THREAD

**Issue by jullduxster** [novotnyllc/Zeroconf#112] opened 2019-02-01 15:55 UTC
I'm trying to use this library for mDNS discovery on a manufacturing machine that has multiple NICs.

The problem is, one NIC is for a local network that consists just of the manufacturing machine / Device being manufactured, and the other NIC is connected to our entire network.

Since the library sends out messages over all network interfaces, our manufacturing machine sees the devices on our main network and can't differentiate between those and the one on its local network.

It would be nice if we were able to select which network interface we wanted to use in the library.

**Comment by pix64** [comment] 2019-02-02 02:05
I think the issue is having a common network interface object among the different platforms.

I've made a personal dork which allows me to only discover devices on my test network. I only need .NET Framework, so the rest of the platforms were stripped. I've hastily thrown it on Github.

On top of allowing you to only perform mDNS on a specific network:

* Can specify IN class (not all devices respond to ANY)
* Send Query SRV and TXT requests
* Handle SRV and TXT responses

https://github.com/pix64/Zeroconf

Hopefully, it'll be of some use to you.

**Comment by notronrj** [comment] 2020-05-07 18:33
> I think the issue is having a common network interface object among the different platforms.
> 
> I've made a personal dork which allows me to only discover devices on my test network. I only need .NET Framework, so the rest of the platforms were stripped. I've hastily thrown it on Github.
> 
> On top of allowing you to only perform mDNS on a specific network:
> 
> * Can specify IN class (not all devices respond to ANY)
> * Send Query SRV and TXT requests
> * Handle SRV and TXT responses
> 
> https://github.com/pix64/Zeroconf
> 
> Hopefully, it'll be of some use to you.

I'm interested in the work you did, but the github link appears broken.

**Comment by pix64** [comment] 2020-05-07 18:55
I've restored the repo more or less.

**Comment by clairernovotny** [comment] 2020-06-13 15:22
Fixed in #156

**Closed by clairernovotny** 2020-06-13 15:22 UTC
